config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :quotes
  root 'quotes#random'
  get 'about' => 'static_pages#about'
  post 'about' => 'static_pages#create_message'
  namespace :api do
    namespace :v1 do
      jsonapi_resources :precepts, only: [:index, :show] do
        collection do
          get :random
        end
      end
    end
  end

  devise_scope :user do
    get 'users/admin' => 'users/registrations#index'
    get 'users/access/:id' => 'users/registrations#access', as: 'get_user_access'
    patch 'users/access/:id' => 'users/registrations#access_update'
  end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :quote, presence: true, length: {minimum: 2, maximum: 500}
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!, except: [:random, :show]
  attr_accessor :tweet_text

  def show
    @quote = Quote.find_by_id(params[:id])
  end

  def random
    @quote = Quote.order("RANDOM()").first
    @tweet_text = @quote.quote + ' --' + @quote.author
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      render :new, status: :unprocessable_entity
    else
      redirect_to quotes_path, notice: 'Precept added!' 
    end
  end

  def new
    @quote = Quote.new
  end

  def index
    @quotes = Quote.all
  end

  def edit
    @quote = Quote.find_by_id(params[:id])
  end

  def update
    @quote = Quote.find_by_id(params[:id])
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: 'Precept edited successfully!' 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote = Quote.find_by_id(params[:id])
    @quote.destroy
    redirect_to quotes_path, notice: 'Precept deleted.' 
  end

  private
    def quote_params
      params.require(:quote).permit(:quote, :author, :book)
    end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/edit.html.erb
<div class="col-sm-offset-3 col-sm-6">
  <h2>Edit Precept</h2><br/>
</div>
<div class="clear">
<p>The author should be the original source of the quote. If the precept was submitted by a student in the story (ie original to RJ Palacio), use "" around the name, e.g. "August Pullman".
</p>

<%= form_for @quote do |f| %>

  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@quote.errors.count, "error") %> prohibited this precept from being saved:</h3>
      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%=f.label :quote %>
  <%=f.text_field :quote, class: 'form-control' %>
  <br/>
  <%=f.label :author %>
  <%=f.text_field :author, class: 'form-control' %>
  <br/><br/>
  <%=f.submit "Save", class: 'btn btn-primary' %>
<% end %>
<br/>
<%= link_to 'Cancel', quotes_path %>

app/views/quotes/index.html.erb
<div class="col-sm-offset-3 col-sm-6">
  <h2>Precept Index</h2><br/>
</div>
<div class="clear">

<%= link_to "New Precept", new_quote_path, class: 'btn btn-primary' %>
<br/>

<br/>
<div class="table-responsive">
  <table class="table">
    <tr>
      <th style="border-top-style:none">Precept</th>
      <th style="border-top-style:none">Source</th>
      <th style="border-top-style:none">Edit</th>
      <th style="border-top-style:none">Delete</th>
    </tr>
    <% @quotes.each do |q| %>
      <tr>
        <td class="col-sm-6"><%=q.quote %></td>
        <td class="col-sm-2"><%= q.author %></td>
        <td class="col-sm-1">
          <%= link_to edit_quote_path(q) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td class="col-sm-1">
          <%= link_to quote_path(q), method: :delete, data: {confirm: "Are you sure?"} do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/quotes/new.html.erb
<div class="col-sm-offset-3 col-sm-6">
  <h2>Enter a New Precept</h2><br/>
</div>
<div class="clear">
<p>The author should be the original source of the quote. If the precept was submitted by a student in the story (ie original to RJ Palacio), use "" around the name, e.g. "August Pullman".
</p>
<%= form_for @quote do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@quote.errors.count, "error") %> prohibited this precept from being saved:</h3>
      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%=f.label :quote %>
  <%=f.text_field :quote, class: 'form-control' %>
  <br/>
  <%=f.label :author %>
  <%=f.text_field :author, class: 'form-control' %>
  <br/><br/>
  <%=f.submit "Create New Precept", class: 'btn btn-primary' %>
<% end %>

<br/>
<%= link_to 'Cancel', quotes_path %>

app/views/quotes/random.html.erb
<div class="jumbotron">
  <h2> 
    <span>
      <% if @quote %>
        Precept # <%= @quote.id %>
      <% else %>
        Precept # 0
      <% end %>
    </span>
  </h2>
  <% if @quote %>
    <h1 id='precept-quote' class="precept"> <%= @quote.quote %> </h1>
    <h2 class="pull-right precept-author"> -- <%= @quote.author %> </h2>
  <% else %>
    <h1 class="precept">There are no quotes in the database. Create some!</h1>
  <% end %>
    <br class="clear" />
  <br />
  <br />
  <a href="https://twitter.com/share" data-size="large" data-text="<%= @tweet_text%>" data-url="http://wondersays.herokuapp.com" data-hashtags="choosekind" data-show-count="false" class="twitter-share-button">
  </a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>  
<div class="container">
  <div class="text-center">
    <a href=<%= root_path %> class='btn btn-default' role="button" id='next-quote'><i class="fa fa-refresh fa-2x" style="vertical-align: middle;"></i>&nbsp;Show Another!</a>
  </div>
</div>
<br class="clear" />
<br />
<div class="footer-blurb">
  <a href=<%= about_path %>>
    The quotes shown here are gathered from Wonder, by R J Palacio.  
  </a>
</div>     

<script>
  $(document).ready(function(){
    $.ajax({
      url: 'api/v1/precepts/random.json',
      //url: 'http://wondersays.herokuapp.com/api/v1/precepts/random.json',
      type: 'GET',
      dataType: 'jsonp',
      jsonp: 'callback',
      jsonpCallback: 'jsonpCallback',
      success: function(){
      }, 
      error: function (data) {
        console.log('Failed to get quote!');
      }
    });
  });
  function jsonpCallback(data){
    //console.log(data.quote);
  }
</script>

app/views/quotes/show.html.erb
<% if @quote %>
  <h2><%= @quote.quote %></h2>
  <h3><%= @quote.author %></h3>
<% end %>