config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :quotes
  root 'quotes#random'
  get 'about' => 'static_pages#about'
  post 'about' => 'static_pages#create_message'
  namespace :api do
    namespace :v1 do
      jsonapi_resources :precepts, only: [:index, :show] do
        collection do
          get :random
        end
      end
    end
  end

  devise_scope :user do
    get 'users/admin' => 'users/registrations#index'
    get 'users/access/:id' => 'users/registrations#access', as: 'get_user_access'
    patch 'users/access/:id' => 'users/registrations#access_update'
  end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wondersays</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>     
        <%= link_to 'wondersay', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">      
        </ul> 
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Precepts', quotes_path %>
          </li>
          <li>
            <%= link_to 'Users', users_admin_path %>
          </li>          
          <li>
            <%= link_to 'Exit Admin Mode', destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

<div class="container">
  <% if flash[:error].present? %>
    <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>

  <% if flash[:notice].present? %>
    <div class="col-xs-10 col-xs-offset-1 alert alert-info" id="wtf">
      <%= flash[:notice].html_safe %>
    </div>
  <% end %>

  <%= yield %>
</div>


  

</body>
</html>